### PR TITLE
Don't emit atomics for thread-safe assignment patterns

### LINKED ISSUE #316: taco generates invalid "#pragma omp atomic" for Store ops
In the `scheduling_eval.test_spmvCPU_temp` test, Taco generates the following code:

```C
    #pragma omp atomic
    y_vals[i] = tjy_val;
```

On Debian bullseye (testing), this fails to compile with the following error:

```
[ RUN      ] scheduling_eval.test_spmvCPU_temp
/tmp/taco_tmp_4Ids2M/1wry7ti8f7ci.c: In function ‘compute’:
/tmp/taco_tmp_4Ids2M/1wry7ti8f7ci.c:137:24: error: invalid form of ‘#pragma omp atomic’ before ‘;’ token
  137 |     y_vals[i] = tjy_val;
      |                        ^
Error at /home/infinoid/workspace/taco/taco/src/codegen/module.cpp:154 in compile:
 Compilation command failed:
gcc-10 -O3 -ffast-math -std=c99 -shared -fPIC -fopenmp /tmp/taco_tmp_4Ids2M/1wry7ti8f7ci.c  -o /tmp/taco_tmp_4Ids2M/1wry7ti8f7ci.so -lm
returned 256
[  FAILED  ] scheduling_eval.test_spmvCPU_temp (190 ms)
```

The test passes on ubuntu-20.04 and ubuntu-18.04.  I think they added some new checks in the new compiler version.  (gcc and libgomp1 version 10.2.0)

`git bisect` indicates that the test starts failing in e976ecb.  Prior to that commit, the code generated was:

```C
    #pragma omp atomic
    y_vals[i] = y_vals[i] + tj_val;
```

This compiles successfully; the new syntax does not.

This `Store` op doesn't appear to need atomics.  Each thread has different values of `i`, and this is the only place `y_vals[i]` is accessed, so the accesses should be safe.  But if it does need it, adding a "write" at the end (`#pragma omp atomic write`) is enough to make the compiler happy again.

For convenience, I posted generated source files for current and "last known working" versions at https://gist.github.com/Infinoid/1692a5963997fa5bccbaf42b0b29cc67 .

### PR DESCRIPTION
**Pull request by Infinoid**
This attempts to fix #316.

It prevents a `#pragma omp atomic` from being emitted for the assignment to `y_vals[i]` in this case:
```c
$ bin/taco 'y(i) = A(i, j) * x(j)' -f=A:ds -s='parallelize(i, CPUThread, Atomics)'
// Generated by the Tensor Algebra Compiler (tensor-compiler.org)

int compute(taco_tensor_t *y, taco_tensor_t *A, taco_tensor_t *x) {
  int y1_dimension = (int)(y->dimensions[0]);
  double* restrict y_vals = (double*)(y->vals);
  int A1_dimension = (int)(A->dimensions[0]);
  int* restrict A2_pos = (int*)(A->indices[1][0]);
  int* restrict A2_crd = (int*)(A->indices[1][1]);
  double* restrict A_vals = (double*)(A->vals);
  int x1_dimension = (int)(x->dimensions[0]);
  double* restrict x_vals = (double*)(x->vals);

  #pragma omp parallel for schedule(runtime)
  for (int32_t i = 0; i < A1_dimension; i++) {
    double tjy_val = 0.0;
    for (int32_t jA = A2_pos[i]; jA < A2_pos[(i + 1)]; jA++) {
      int32_t j = A2_crd[jA];
      tjy_val += A_vals[jA] * x_vals[j];
    }
    y_vals[i] = tjy_val;
  }
  return 0;
}
```

Because each thread gets its own value of `i`, no other thread will assign to that location, and recent compilers treat an atomic pragma as invalid there.  See #316 for details.

Are there any other cases this doesn't cover?  All tests pass for me when configuring with `-DOPENMP=ON -DPYTHON=ON`.

### CODE REVIEW

**Comment by stephenchouca** [comment]
This patch seems to generate incorrect code for expressions like `'y(j) = A(i,j,k) * x(k)' -s='parallelize(j, CPUThread, Atomics)'`, which still require atomics even after scalar promotion (the generate code omits the required atomic pragma).

More fundamentally though, I wonder if we should instead just fix the lowerer so that it won't emit unnecessary atomic pragmas for (non-reduction) assignments. That way, the bug would be fixed even if, for instance, a user decides to manually invoke the lowerer with concrete index notation that has an assignment inside a Forall statement synchronized with atomics. This should only require modifying a few lines in `lowerAssignment`; I can take a stab at it if you'd like.

**Comment by Infinoid** [comment]
> This should only require modifying a few lines in `lowerAssignment`; I can take a stab at it if you'd like.

Sure, please do.  And I'll happily add your example as a test case.

**Comment by stephenchouca** [comment]
> Sure, please do. And I'll happily add your example as a test case.

That'd be great, thanks!

**Comment by Infinoid** [comment]
Your patch works, I added the test case in #402.  Thanks!

Canceling PR in favor of 0a48d17.
